---
repos:
  # --- Basic sanity checks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: excalidraw_diagrams.excalidraw
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  # --- Python formatting (Black) ---
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  # --- Python linting (Flake8) ---
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: [--max-line-length=100]

  # --- Dockerfile linting ---
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint

  # --- Shell script checks ---
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
