name: Build and Test

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit safety bandit pyup

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -f tests/ ]; then
            pip install pytest
            pytest
          else
            echo "No tests found, skipping pytest"
          fi

      - name: Run safety (Python vulnerability check)
        run: safety check --full-report

      - name: Run bandit (Python security linter)
        run: bandit -r src/ 

      - name: Run pyup check for vulnerabilities
        run: pyup safety check --full-report
